### ISSUE TITLE
Multi Domain issues

### ISSUE THREAD

**Issue by HenryAveMedi** [t3solution/t3sbootstrap#130]
I'm setting a multi-domain site, and I'm having issues with this extension. Until now i had used multi-domain inside the main domain because it was needed, but in this new project it had to be in the first page tree level. I'm trying to configure it (because i override mostly in the constants) and after many issues i had manage to at least see the website in FE, but then the BE wasn't showing Jumbotron or Footer colPos (Event though activated).

I deactivated my constants and configured everything in the backend module and still nothing. 

So i tried moving it inside the id 1 page and everything would show as expected then moved out and back to square one, not showing colPos, but now I'm getting "The main configuration has to be created first on the root page." in the FE…… BE module shows the t3s config when i click the page, but FE shows that warning………

I cant remove the t3s config from a page to try to add it again, so i had to start all over again, new page, new site and domain configuration, new template, etc……… same error again……

I'm lost……… any help? i realize not many sites need multi domain, and maybe not many admins hit this wall, but i would appreciate any help

Thank you

-----------
TYPO3 10.4.15
t3sbootstrap  4.6.0 (4.6.2 updates my container extension, and there's a bug there when loading pages with background container, it searches for partial Header with //Header so it breaks the backend, not sure if this is a bug in t3s or container ext im dealing with this multidomain problem 1st )

-----------
**UPDATE:** Note to self…… never move main configs in and out of PageTree

now the original t3sconfig of page id=1 is completely broken………
does this extension really need to work like this? why is it not possible for it to work with only constants and setup as any other extension in typo3

Or could you at least allow to delete a main t3sbootstrap config so it's possible to basically reset a config?

-----------
**UPDATE:** After hard work trying to recover and fix the main tree, uninstalling, deleting bootstrap tables and installing again. made some new tries.

Multidomain 2nd config doesn't work properly in BE view, i can't get access to wither jumbotron nor footer cols. Even if unter the main configuration of 2nd domain I do config override in subpage, it still doesn't show jumbotron nor footer cols in BE……

Any help is very much appreciated

**Comment by t3solution** [comment]
Did you notice the following bugfix?:
https://github.com/t3solution/t3sbootstrap/commit/c1c8643f1f64204e3a54a151eaadafe21f8b408c

**Comment by HenryAveMedi** [comment]
no, but how should i do in my case, because if i update t3s it updates container ext as well, and as described before… that has a BE bug when fetching partial /Header (if u use a background container in the page)

**Comment by t3solution** [comment]
You have to fix (only) this https://github.com/t3solution/t3sbootstrap/commit/c1c8643f1f64204e3a54a151eaadafe21f8b408c
and everything should be working as expected!

**Comment by HenryAveMedi** [comment]
i updated both extensiond again, i'm not getting the / Header bug anymore, but still can't see jumbotron or footer of 2nd domain in BE

**Comment by t3solution** [comment]
... if your site is online, you can give me the access data and i will take a look at it!

**Comment by HenryAveMedi** [comment]
I'm updating it manually already, just gotta remember in the next update in case something crashes

**Comment by HenryAveMedi** [comment]
hmmmm, no change, i oppened and resaved the config of both domains, no change
should the "t3sbconstants.typoscript" look any different? coz at first glance, it doesn't, or should i rather delete that ts file and make a new config in BE module?

**Comment by t3solution** [comment]
... after the BUGFIX you have to open any T3SB Config and open "Edit this configuration" and save it again!

**Comment by HenryAveMedi** [comment]
> hmmmm, no change, i oppened and resaved the config of both domains, no change
> should the "t3sbconstants.typoscript" look any different? coz at first glance, it doesn't, or should i rather delete that ts file and make a new config in BE module?
> 
> [65 in tree.rootLineIds]
> bootstrap.config.uid = 2
> bootstrap.config.updated = 1
> bootstrap.config.gridupdated = 1
> bootstrap.config.homepageUid = 65
> .
> .
> bootstrap.config.jumbotronEnable = 1
> .
> .
> bootstrap.config.footerEnable = 1
> .
> .
> bootstrap.config.navbarBreakpointWidth = 768
> [END]

yeh, i did that already as explained in this reply……… it had no changes, still unable to see the jumbotron and footer in BE

**Comment by t3solution** [comment]
New version 5 - new issues!
