### ISSUE TITLE
PHP Warning: Undefined array key "t3sbconcatenate" in IsInline.php line 45

### ISSUE THREAD

**Issue by nhovratov** [t3solution/t3sbootstrap#405]
PHP Warning: Undefined array key "t3sbconcatenate" in /var/www/html/vendor/t3sbs/t3sbootstrap/Classes/EventListener/AssetRenderer/IsInline.php line 45

**Comment by t3solution** [comment]
Should be fixed with v5.3.16!

**Comment by Lutzion** [comment]
I still have the same error message after 
- updating to v5.3.16 
- clearing all caches by gui and 
- even deleting the complete folder typo3temp/var/cache.

Which requirements have to be fullfilled to get rid of the warning?

**Comment by t3solution** [comment]
You can make the setting here:
<img width="956" alt="Bildschirmfoto 2024-10-14 um 17 40 19" src="https://github.com/user-attachments/assets/bb52576c-7930-4172-be8a-4dd96ed2e7d2">

**Comment by Lutzion** [comment]
Thank you for your fast response.
Of course i use
t3sb.t3sbconcatenate with "Compress" in T3SB config,
but still get this warning.

**Comment by t3solution** [comment]
Here is the BUGFIX: https://github.com/t3solution/t3sbootstrap/commit/b77f4bddb31e362378e503c4d9d79de3a31bf33a

**Comment by Lutzion** [comment]
Looks better. Thank you
